version: '3'

services:
  db:
    image: mysql:5.7
    ports:
      - '3306:3306'
    environment:
       MYSQL_DATABASE: 'docker-db'
       MYSQL_USER: 'root'
       MYSQL_PASSWORD: 'venky@123'
       MYSQL_ROOT_PASSWORD: 'venky@123'

  nginx:
    image: nginx:latest
    container_name: ng01
    ports:
      - "8001:80"
    volumes:
      - .:/music_service
      - ./config/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - web

  web:
    build: .
    #command: bash -c "python3 mysiteproject/manage.py makemigrations && python3 mysiteproject/manage.py migrate && python3 mysiteproject/manage.py runserver 0.0.0.0:8000"
    container_name: music_service
    volumes:
      - .:/music_service
    ports:
      - "8000:8000"
    depends_on:
      - db
    command : bash -c "python3 mysiteproject/manage.py collectstatic --no-input && gunicorn mysiteproject.mysiteproject.wsgi -b 0.0.0.0:8000"
    #command: "gunicorn --workers=3 --bind=0.0.0.0:8000 mysiteproject.wsgi:application -error-logfile=gunicorn.log -p app.pid"

